### ISSUE TITLE
[Bug] [Help resolving missing deps needed]  Exception in `JavaTimeModule`

### ISSUE THREAD

**Issue by hellboy81** [FasterXML/jackson-modules-java8#101]
````java
Deployed artifacts:

META-INF/lib/jackson-annotations-2.9.8.jar
META-INF/lib/jackson-core-2.9.8.jar
META-INF/lib/jackson-databind-2.9.8.jar
META-INF/lib/jackson-datatype-jsr310-2.9.8.jar
META-INF/lib/jackson-datatype-threetenbp-2.6.4.jar

// com.fasterxml.jackson.datatype.jsr310.JavaTimeModule

// then serializers:
addSerializer(Duration.class, DurationSerializer.INSTANCE);
addSerializer(Instant.class, InstantSerializer.INSTANCE);
addSerializer(LocalDateTime.class, LocalDateTimeSerializer.INSTANCE);
addSerializer(LocalDate.class, LocalDateSerializer.INSTANCE);
addSerializer(LocalTime.class, LocalTimeSerializer.INSTANCE);
addSerializer(MonthDay.class, MonthDaySerializer.INSTANCE);
addSerializer(OffsetDateTime.class, OffsetDateTimeSerializer.INSTANCE);
addSerializer(OffsetTime.class, OffsetTimeSerializer.INSTANCE);
addSerializer(Period.class, new ToStringSerializer(Period.class)); // Causes exception
addSerializer(Year.class, YearSerializer.INSTANCE);
addSerializer(YearMonth.class, YearMonthSerializer.INSTANCE);

java.lang.IllegalAccessError: tried to access method com.fasterxml.jackson.databind.ser.std.StdSerializer.<init>(Ljava/lang/Class;)V from class com.fasterxml.jackson.datatype.jsr310.JavaTimeModule

1669833 [INFO] org.codehaus.cargo.maven2.ContainerStartMojo - [talledLocalContainer] java.lang.IllegalAccessError: tried to access method com.fasterxml.jackson.databind.ser.std.StdSerializer.<init>(Ljava/lang/Class;)V from class com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
1669833 [INFO] org.codehaus.cargo.maven2.ContainerStartMojo - [talledLocalContainer] 	at com.fasterxml.jackson.datatype.jsr310.JavaTimeModule.<init>(JavaTimeModule.java:168)

**Comment by GedMarc** [comment]
not related to : https://github.com/FasterXML/jackson-modules-java8/issues/99#issuecomment-461680457 ?

**Comment by GedMarc** [comment]
@hellboy81 try with  <artifactId>jackson-datatype-jdk8</artifactId> instead of jsr310

**Comment by hellboy81** [comment]
due on `JavaTimeModule` shoul I use last version?

**Comment by hellboy81** [comment]
```java
329241 [INFO] org.codehaus.cargo.maven2.ContainerStartMojo - [talledLocalContainer] java.lang.VerifyError: Cannot inherit from final class
329241 [INFO] org.codehaus.cargo.maven2.ContainerStartMojo - [talledLocalContainer] 	at com.fasterxml.jackson.datatype.jdk8.Jdk8Module.setupModule(Jdk8Module.java:30)
329241 [INFO] org.codehaus.cargo.maven2.ContainerStartMojo - [talledLocalContainer] 	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:550)
```

**Comment by GedMarc** [comment]
This is a custom class inheriting the jdk 8/jsr310 module?

**Comment by GedMarc** [comment]
```
ObjectMapper mapper = new ObjectMapper();
		mapper.registerModule(new JavaTimeModule());
		mapper.registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module());

		TimeTestClass test = new TimeTestClass();
		System.out.println(mapper.writeValueAsString(test));
```

This works fine - I think your container is trying to proxy the module class? Or you are extending the module class instead of copy and paste it.
What cargo module are you running?

**Comment by cowtowncoder** [comment]
That certainly sounds like a version mismatch: that is, a dependency compiled against certain `jackson-databind` version being included with different (usually older) minor version of `jackson-databind`. Note that minor versions of different components SHOULD match, although most of the time they need to be partially ordered: that is, `jackson-databind` 2.7, for example, is ok with datatype modules 2.7.x, 2.8.x and 2.9.x -- but NOT the other way around.

**Comment by cowtowncoder** [comment]
Btw, this:

    META-INF/lib/jackson-datatype-threetenbp-2.6.4.jar

looks suspicious: if it follows same versioning scheme, you should include 2.9.x version (or whatever is latest after 2.6)

**Comment by huyle1097** [comment]
Thank you @cowtowncoder ,
I have several wars running on a Wildfly server in my scenario.
And because my new war package uses a lib that contains the new Jackson version, whilst other legacy wars used the old one, it caused the issue.
