### ISSUE TITLE
NON_ABSENT works for Optional<Long> but not OptionalLong

### ISSUE THREAD

**Issue by prdoyle** [FasterXML/jackson-modules-java8#45]
When I use `NON_ABSENT` for a field that is `OptionalLong.empty()`, I get this:

```
Caused by: java.util.NoSuchElementException: No value present
	at java.util.OptionalLong.getAsLong(OptionalLong.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:687)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
```

With `Optional<Long>`, a value that is `empty()` is skipped as expected.

**Comment by prdoyle** [comment]
Version:

```
<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-databind</artifactId>
	<version>2.9.2</version>
</dependency
```

**Comment by cowtowncoder** [comment]
And code... ?

**Comment by cowtowncoder** [comment]
Can not reproduce with simple example, need reproduction (unit test or such).

**Comment by cowtowncoder** [comment]
Need reproduction; may be reopened with one.
