### ISSUE TITLE
Cannot read read written Optionals with StdTypeResolverBuilder 

### ISSUE THREAD

**Issue by isopov** [FasterXML/jackson-modules-java8#86]
The following test fails on Jackson 2.9.7 and passes on 2.8.11:
```
    @Test
    public void test() throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        mapper.setDefaultTyping(
                new StdTypeResolverBuilder()
                        .init(JsonTypeInfo.Id.CLASS, null)
                        .inclusion(JsonTypeInfo.As.WRAPPER_OBJECT)
        );
        mapper.registerModule(new Jdk8Module());
        String json = mapper.writeValueAsString(new Foo(Optional.of(1)));
        System.out.println(json);
        mapper.readValue(json, Foo.class);
    }

    public static class Foo {
        private Optional<Integer> bar;

        public Foo() {
        }

        public Foo(Optional<Integer> bar) {
            this.bar = bar;
        }

        public Optional<Integer> getBar() {
            return bar;
        }

        public void setBar(Optional<Integer> bar) {
            this.bar = bar;
        }
    }
```
Complete runnable project with this test-case can be found on https://github.com/isopov/jackson-optional-test

**Comment by isopov** [comment]
Added workaround, involving copy&pasting classes from 2.8.11 - https://github.com/isopov/jackson-optional-test/blob/workaround/src/test/java/com/example/OptionalJacksonTest.java

Still proper fix will be highly appreciated.

**Comment by cowtowncoder** [comment]
I will have to say that it is quite possible that combination of polymorphic type in `Optional` for root value may be unsupportable. I would strongly recommend not using that combination: partly since root values have significant challenges wrt type erasure, and partly as `Optional`s are challenging in their own right.

In fact I am considering adding a warning that polymorphic type handling is not recommended to be used for root values at all.

Having said that: I will try to figure out if this can be made to work correctly (although depending on changes they might only be made to 2.9 branch), and I hope this is the case.

Thank you for reporting the problem.

------

**EDIT**: Looking at this further, `Optional` is NOT used as root value. So that's not the problem.

**Comment by cowtowncoder** [comment]
To help future work, output looks like:

```
{"com.fasterxml.jackson.datatype.jdk8.PolymorphicOptionalTest$Foo":{"bar":1}}
```

and that would seem to be missing type information for contents, somehow.

**Comment by cowtowncoder** [comment]
@JooHyukKim this might be worth looking into as well.

**Comment by JooHyukKim** [comment]
Ah so this is how we want the output object is in 2.8.

```json
{
    "com.fasterxml.jackson.datatype.jdk8.OptionalStdTypeResolverBuilder86Test$Foo": {
        "bar": {
            "java.util.Optional": 1
        }
    }
}
```

If we try to read above JSON output from 2.8, in later version, throws error saying...

```log
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'java.util.Optional' as a subtype of `java.lang.Integer`: Not a subtype
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 4, column: 13] (through reference chain: com.fasterxml.jackson.datatype.jdk8.OptionalStdTypeResolverBuilder86Test$Foo["bar"])

	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:2041)
	at com.fasterxml.jackson.databind.DatabindContext._throwNotASubtype(DatabindContext.java:291)
	at com.fasterxml.jackson.databind.DatabindContext.resolveAndValidateSubType(DatabindContext.java:252)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:76)
```

**Comment by cowtowncoder** [comment]
Hmmmh. Now that I think about this, there's a problem... Although we do need the type id of the contained value, we also need to know there's `Optional` in-between.
So not 100% sure what type id is needed. It's almost as if we needed `Optional<Integer>`.
To further complicate things tho, `Integer` is so-called "natural" type, for which no type id is to be output. Ugh.

I also realized that the test case is incomplete; it doesn't seem to verify actual contents.
